volumes:
  sierra_grande_local_postgres_data: {}
  sierra_grande_local_postgres_data_backups: {}
  sierra_grande_local_redis_data: {}
  sierra_grande_local_solr_data:

services:
  django: &django
    build:
      context: .
      dockerfile: ./compose/local/django/Dockerfile
      args:
        - RUN_ON_BUILD=true
    image: sierra_grande_local_django
    container_name: sierra_grande_local_django
    depends_on:
      - postgres
      - redis
      - mailpit
      - solr
    volumes:
      - .:/app:z
    env_file:
      - ./.envs/.local/.django
      - ./.envs/.local/.postgres
    ports:
      - "5678:5678"  # Puerto para debugpy
      - '8000:8000'
    command: /start

  postgres:
    build:
      context: .
      dockerfile: ./compose/production/postgres/Dockerfile
    image: sierra_grande_production_postgres
    container_name: sierra_grande_local_postgres
    ports:
      - '5432:5432'
    volumes:
      - sierra_grande_local_postgres_data:/var/lib/postgresql/data
      - sierra_grande_local_postgres_data_backups:/backups
    env_file:
      - ./.envs/.local/.postgres

  mailpit:
    image: docker.io/axllent/mailpit:latest
    container_name: sierra_grande_local_mailpit
    ports:
      - "8025:8025"

  redis:
    image: docker.io/redis:6
    container_name: sierra_grande_local_redis

    volumes:
      - sierra_grande_local_redis_data:/data

  solr:
    build:
      context: .
      dockerfile: ./compose/local/solr/Dockerfile
    image: sierra_grande_local_solr
    container_name: sierra_grande_local_solr

    ports:
      - '8983:8983'
    volumes:
      - sierra_grande_local_solr_data:/var/solr

  celeryworker:
    <<: *django
    image: sierra_grande_local_celeryworker
    container_name: sierra_grande_local_celeryworker
    depends_on:
      - redis
      - postgres
      - mailpit
    ports: []
    command: /start-celeryworker

  celerybeat:
    <<: *django
    image: sierra_grande_local_celerybeat
    container_name: sierra_grande_local_celerybeat
    depends_on:
      - redis
      - postgres
      - mailpit
    ports: []
    command: /start-celerybeat

  flower:
    <<: *django
    image: sierra_grande_local_flower
    container_name: sierra_grande_local_flower
    ports:
      - '5555:5555'
    command: /start-flower
